name: comic_snagger
channels:
  - defaults
dependencies:
  - beautifulsoup4=4.6.0
  - flake8=3.5.0
  - isort=4.3.4
  - pylint=1.9.2
  - pytest=3.6.2
  - python=3.6.6
  - requests=2.19.1
  - pip:
    - black==18.6b4
